# @trace SPEC-07
"""Orchestration script generation for multi-agent workflows.

Generates orchestrate.sh that fans out parallel groups to multiple
claude -p processes with verification gates between phases.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def generate_orchestration_script(
    data: dict[str, Any],
    parallel_slots: int = 3,
) -> str:
    """Generate a multi-agent orchestration script.

    The script:
    1. Fans out parallel groups to claude -p processes
    2. Waits for phase completion
    3. Runs verification gates (task closed, no new blockers)
    4. Halts on verification failure

    Args:
        data: Validated decomposition output dict.
        parallel_slots: Max concurrent agents.

    Returns:
        Shell script string for orchestrate.sh.
    """
    tasks = data.get("tasks", [])
    groups = data.get("parallel_groups", [])

    # If no explicit parallel groups, create phases from dependency layers
    if not groups:
        groups = _infer_phases(tasks)

    lines: list[str] = []
    lines.append("#!/usr/bin/env bash")
    lines.append("set -euo pipefail")
    lines.append(
        "# Generated by spec-decompose --orchestrate. "
        "Run decompose-plan.sh first to create work items."
    )
    lines.append("")
    lines.append(f"PARALLEL_SLOTS=${{PARALLEL_SLOTS:-{parallel_slots}}}")
    lines.append("")

    # Build task ID mapping (number -> variable name)
    # Assumes decompose-plan.sh has been run and IDs are in Beads
    lines.append("# Retrieve task IDs from Beads")
    lines.append(
        "TASK_IDS=$(bd list --status open --json 2>/dev/null "
        "| jq -r '.[].id' || true)"
    )
    lines.append('if [ -z "$TASK_IDS" ]; then')
    lines.append(
        '  echo "No open tasks found. Run decompose-plan.sh first."'
    )
    lines.append("  exit 1")
    lines.append("fi")
    lines.append("")

    # Generate phases
    for i, group in enumerate(groups, 1):
        group_name = group.get("name", f"phase-{i}")
        task_numbers = group.get("tasks", [])

        if not task_numbers:
            continue

        lines.append(f'echo "=== Phase {i}: {group_name} ==="')
        lines.append("parallel_pids=()")
        lines.append("")

        for tn in task_numbers:
            lines.append(f"# Task T{tn}")
            lines.append(
                f'TASK_ID=$(bd list --status open --json 2>/dev/null '
                f'| jq -r \'[.[] | select(.title | test("T{tn}|task.*{tn}"; "i"))][0].id // empty\' || true)'
            )
            lines.append('if [ -n "$TASK_ID" ]; then')
            lines.append(
                f'  claude -p "You are working on task $TASK_ID. '
                f"Run 'bd show $TASK_ID' for full details. "
                f'Follow the task-executor workflow." '
                f"--allowedTools 'Bash,Read,Write,Edit' &"
            )
            lines.append("  parallel_pids+=($!)")
            lines.append(
                f'  echo "Started agent for T{tn}: $TASK_ID (PID: $!)"'
            )
            lines.append("fi")
            lines.append("")

        # Wait for phase
        lines.append(f'echo "Waiting for Phase {i} to complete..."')
        lines.append("exit_code=0")
        lines.append('for pid in "${parallel_pids[@]}"; do')
        lines.append(
            '  wait "$pid" || { echo "WARNING: Agent $pid exited non-zero"; exit_code=1; }'
        )
        lines.append("done")
        lines.append("")

        # Verification gate
        lines.append(f'echo "Verifying Phase {i}..."')
        lines.append("phase_ok=true")
        lines.append("")

        # Check for new blockers
        lines.append(
            "NEW_BLOCKERS=$(bd blocked --json 2>/dev/null "
            "| jq -r 'length' || echo 0)"
        )
        lines.append('if [ "$NEW_BLOCKERS" -gt 0 ]; then')
        lines.append(
            f'  echo "WARNING: $NEW_BLOCKERS blocked tasks detected after Phase {i}"'
        )
        lines.append(
            "  # Check if all remaining work is hole-blocked"
        )
        lines.append(
            '  READY=$(bd ready --json 2>/dev/null | jq -r "length" || echo 0)'
        )
        lines.append('  if [ "$READY" -eq 0 ]; then')
        lines.append(
            f'    echo "ERROR: All remaining work blocked. Halting after Phase {i}."'
        )
        lines.append(
            "    echo 'Run: bd list --label hole:human-required --status open'"
        )
        lines.append("    exit 1")
        lines.append("  fi")
        lines.append("fi")
        lines.append("")

    # Final summary
    lines.append('echo "=== Orchestration Complete ==="')
    lines.append("bd stats 2>/dev/null || true")
    lines.append(
        'echo "Run progress-report for a full summary."'
    )
    lines.append("")

    return "\n".join(lines)


def generate_pull_loop_script(
    hole_aware: bool = True,
) -> str:
    """Generate a pull-based orchestration loop.

    Args:
        hole_aware: If True, attempt to resolve agent-resolvable holes
            when no tasks are ready.

    Returns:
        Shell script string.
    """
    lines: list[str] = []
    lines.append("#!/usr/bin/env bash")
    lines.append("set -euo pipefail")
    lines.append("# Pull-based orchestration: agents self-select work via bd ready")
    lines.append("")
    lines.append("while true; do")
    lines.append(
        "  NEXT=$(bd ready --json --limit 1 2>/dev/null "
        "| jq -r '.[0].id // empty' || true)"
    )
    lines.append("")

    if hole_aware:
        lines.append('  if [ -z "$NEXT" ]; then')
        lines.append("    # No tasks ready — check for agent-resolvable holes")
        lines.append(
            "    NEXT=$(bd list --label hole:agent-resolvable "
            "--status open --json 2>/dev/null "
            "| jq -r '.[0].id // empty' || true)"
        )
        lines.append('    if [ -z "$NEXT" ]; then')
        lines.append(
            '      echo "All work complete or blocked on human decisions."'
        )
        lines.append("      break")
        lines.append("    fi")
        lines.append(
            '    echo "No tasks ready. Attempting to resolve hole: $NEXT"'
        )
        lines.append("  fi")
    else:
        lines.append('  if [ -z "$NEXT" ]; then')
        lines.append('    echo "All tasks complete or blocked."')
        lines.append("    break")
        lines.append("  fi")

    lines.append("")
    lines.append('  echo "Working on: $NEXT"')
    lines.append("  bd update \"$NEXT\" --status in_progress")
    lines.append("")
    lines.append(
        '  claude -p "You are working on task $NEXT. '
        "Run 'bd show $NEXT' for full details. "
        'Follow the task-executor workflow." '
        "--allowedTools 'Bash,Read,Write,Edit'"
    )
    lines.append("")
    lines.append(
        "  status=$(bd show \"$NEXT\" --json 2>/dev/null "
        "| jq -r '.status' || echo 'unknown')"
    )
    lines.append('  if [ "$status" != "closed" ]; then')
    lines.append(
        '    echo "WARNING: $NEXT not closed by agent (status: $status)"'
    )
    lines.append("  fi")
    lines.append("done")
    lines.append("")
    lines.append('echo "Orchestration complete."')
    lines.append("bd stats 2>/dev/null || true")
    lines.append("")

    return "\n".join(lines)


def write_orchestration_output(
    data: dict[str, Any],
    parallel_slots: int = 3,
    output_dir: Path | None = None,
    include_pull_loop: bool = False,
) -> list[Path]:
    """Write orchestration scripts.

    Args:
        data: Validated decomposition output.
        parallel_slots: Max concurrent agents.
        output_dir: Output directory (defaults to CWD).
        include_pull_loop: Also generate pull-loop.sh.

    Returns:
        List of generated file paths.
    """
    if output_dir is None:
        output_dir = Path(".")

    paths: list[Path] = []

    # Push-based orchestration
    orch_path = output_dir / "orchestrate.sh"
    orch_path.write_text(
        generate_orchestration_script(data, parallel_slots)
    )
    paths.append(orch_path)

    # Optional pull-based loop
    if include_pull_loop:
        pull_path = output_dir / "pull-loop.sh"
        pull_path.write_text(generate_pull_loop_script(hole_aware=True))
        paths.append(pull_path)

    return paths


def _infer_phases(tasks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Infer parallel phases from task dependencies when no groups are specified.

    Groups tasks into layers where each layer's tasks have no dependencies
    on tasks in the same layer.

    Returns:
        List of phase dicts with 'name' and 'tasks' keys.
    """
    if not tasks:
        return []

    # Build dependency sets
    task_deps: dict[int, set[int]] = {}
    for t in tasks:
        num = t["number"]
        deps = set(t.get("depends_on_tasks", []))
        task_deps[num] = deps

    # Assign layers via topological levels
    assigned: dict[int, int] = {}  # task -> layer
    remaining = set(task_deps.keys())

    layer = 0
    while remaining:
        # Tasks whose deps are all assigned
        ready = {
            t
            for t in remaining
            if all(d in assigned for d in task_deps.get(t, set()) if d in task_deps)
        }
        if not ready:
            # Cycle or missing deps — assign everything to current layer
            ready = remaining.copy()

        for t in ready:
            assigned[t] = layer
        remaining -= ready
        layer += 1

    # Group by layer
    layers: dict[int, list[int]] = {}
    for t, l in assigned.items():
        layers.setdefault(l, []).append(t)

    return [
        {"name": f"phase-{l + 1}", "tasks": sorted(layer_tasks)}
        for l, layer_tasks in sorted(layers.items())
    ]
